name: run

on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Install libudunits2-dev
        run: sudo apt-get install -y libudunits2-dev
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 4
      - name: Run
        env:
          KNMI_API_KEY: ${{ secrets.KNMI_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          source("script.R")
        shell: Rscript {0}
