name: run

on:
  push:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
      - name: run
        run: |
          source("script.R")
        shell: Rscript {0}
